### ISSUE TITLE
Referencing ajaxcrudassets

### ISSUE THREAD

**Issue by christianjosephdalisay** [johnitvn/yii2-ajaxcrud#22]
I created the CRUD using this module. After, the following error occurred.

![capture](https://cloud.githubusercontent.com/assets/7392803/8766159/6ae415f4-2e5f-11e5-9d7a-0c1f0ded9bcf.PNG)

**Comment by johnitvn** [comment]
I don't know why you still get this error. Because it have been fixed in newest version. You can see the index file have line

``` php
use johnitvn\ajaxcrudassets\CrudAsset; 
```

and change it to

``` php
use johnitvn\ajaxcrud\CrudAsset; 
```

See:
[https://github.com/johnitvn/yii2-ajaxcrud/blob/master/src/generators/default/views/index.php#L21](https://github.com/johnitvn/yii2-ajaxcrud/blob/master/src/generators/default/views/index.php#L21)

**Comment by christianjosephdalisay** [comment]
Before submiting this issue I also tried changing to johnitvn\ajaxcrud\CrudAsset. Still, it does not work.

**Comment by johnitvn** [comment]
Let try remove and reinstall yii2-ajaxcrud. I think you aren't in right version

**Comment by christianjosephdalisay** [comment]
Got it.
