### ISSUE TITLE
[v3.0] Any ideal for version 3.0?

### ISSUE THREAD

**Issue by johnitvn** [johnitvn/yii2-ajaxcrud#29]

**Comment by drsdre** [comment]
An option to generate grid's with Kartik-v's DynaGrid (http://demos.krajee.com/dynagrid) would be very welcome.

**Comment by Enrica-r** [comment]
First of all: Thank you very much for the great extension. It's an universal component to use forms in modal boxes instead of changing the page.

If I don't want to use the gii generator I have to add in each view two code fragments:
1. `CrudAsset::register($this);`
2. `php <?php Modal::begin([
    "id"=>"ajaxCrubModal",
    "footer"=>"",// always need it for jquery plugin
])?>`

I propose to encapsulate this in a Yii2 widget as usual like:

``` php
CrudAsset::widget([
 'id' => 'chooseable',
 'rolename' => 'modal-remote',
 'size' => 'modal-lg',
 'header' => 'some text',
 'footer' => 'some text',
 'after-success' => 'function{}',
 'other options' => ???
]);
```

This widget should register the Asset Bundle automatically once and places the modal widget on the page. Internally all options should be set by default. With different id and rolename it should be possible to have different modals on the same page.

The size option could have values like: `small`, `large`, `modal-lg` or also `xx%` or `xxxpx`. Which should set the width property.

Then you could introduce callback functions in your javascript like `before-load`, `after-success`, `after-error`, `after-close` etc. This gives an option to the programmer to extend with own Javascripts. Example: After creating a new record in modal the programmer could refresh the grid with PJAX. Kartik has this used in some modules. Example see TreeManager (Tree Plugin events): http://demos.krajee.com/tree-manager

I hope you can add my ideas. Again thank you very much.
Enrica
